FROM python:3.9-slim

WORKDIR /app

COPY flask/requirements.txt .  
RUN pip install --no-cache-dir -r requirements.txt

COPY flask/ /app

ENV FLASK_APP=app/app.py
ENV FLASK_RUN_HOST=0.0.0.0

ENV PYTHONPATH=/app

EXPOSE 5000

COPY wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it

CMD [ "wait-for-it", "mysql:3306", "--","flask", "run"]
